// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.programacion2.demo1.entidades;

import ar.edu.um.programacion2.demo1.entidades.Carta;
import ar.edu.um.programacion2.demo1.entidades.CartaDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect CartaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CartaDataOnDemand: @Component;
    
    private Random CartaDataOnDemand.rnd = new SecureRandom();
    
    private List<Carta> CartaDataOnDemand.data;
    
    public Carta CartaDataOnDemand.getNewTransientCarta(int index) {
        Carta obj = new Carta();
        setFondo(obj, index);
        setNumero(obj, index);
        setPalo(obj, index);
        setValor2(obj, index);
        return obj;
    }
    
    public void CartaDataOnDemand.setFondo(Carta obj, int index) {
        String fondo = "fondo_" + index;
        obj.setFondo(fondo);
    }
    
    public void CartaDataOnDemand.setNumero(Carta obj, int index) {
        String numero = "numero_" + index;
        obj.setNumero(numero);
    }
    
    public void CartaDataOnDemand.setPalo(Carta obj, int index) {
        String palo = "palo_" + index;
        obj.setPalo(palo);
    }
    
    public void CartaDataOnDemand.setValor2(Carta obj, int index) {
        Long valor2 = new Integer(index).longValue();
        obj.setValor2(valor2);
    }
    
    public Carta CartaDataOnDemand.getSpecificCarta(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Carta obj = data.get(index);
        Long id = obj.getId();
        return Carta.findCarta(id);
    }
    
    public Carta CartaDataOnDemand.getRandomCarta() {
        init();
        Carta obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Carta.findCarta(id);
    }
    
    public boolean CartaDataOnDemand.modifyCarta(Carta obj) {
        return false;
    }
    
    public void CartaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Carta.findCartaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Carta' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Carta>();
        for (int i = 0; i < 10; i++) {
            Carta obj = getNewTransientCarta(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
