// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.programacion2.demo1.entidades;

import ar.edu.um.programacion2.demo1.entidades.CartaIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CartaIntegrationTest_Roo_Configurable {
    
    declare @type: CartaIntegrationTest: @Configurable;
    
}
