// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.programacion2.demo1.entidades;

import ar.edu.um.programacion2.demo1.entidades.Carta;
import ar.edu.um.programacion2.demo1.entidades.CartaDataOnDemand;
import ar.edu.um.programacion2.demo1.entidades.CartaIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CartaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CartaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CartaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CartaIntegrationTest: @Transactional;
    
    @Autowired
    CartaDataOnDemand CartaIntegrationTest.dod;
    
    @Test
    public void CartaIntegrationTest.testCountCartas() {
        Assert.assertNotNull("Data on demand for 'Carta' failed to initialize correctly", dod.getRandomCarta());
        long count = Carta.countCartas();
        Assert.assertTrue("Counter for 'Carta' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CartaIntegrationTest.testFindCarta() {
        Carta obj = dod.getRandomCarta();
        Assert.assertNotNull("Data on demand for 'Carta' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Carta' failed to provide an identifier", id);
        obj = Carta.findCarta(id);
        Assert.assertNotNull("Find method for 'Carta' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Carta' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CartaIntegrationTest.testFindAllCartas() {
        Assert.assertNotNull("Data on demand for 'Carta' failed to initialize correctly", dod.getRandomCarta());
        long count = Carta.countCartas();
        Assert.assertTrue("Too expensive to perform a find all test for 'Carta', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Carta> result = Carta.findAllCartas();
        Assert.assertNotNull("Find all method for 'Carta' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Carta' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CartaIntegrationTest.testFindCartaEntries() {
        Assert.assertNotNull("Data on demand for 'Carta' failed to initialize correctly", dod.getRandomCarta());
        long count = Carta.countCartas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Carta> result = Carta.findCartaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Carta' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Carta' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CartaIntegrationTest.testFlush() {
        Carta obj = dod.getRandomCarta();
        Assert.assertNotNull("Data on demand for 'Carta' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Carta' failed to provide an identifier", id);
        obj = Carta.findCarta(id);
        Assert.assertNotNull("Find method for 'Carta' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCarta(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Carta' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CartaIntegrationTest.testMergeUpdate() {
        Carta obj = dod.getRandomCarta();
        Assert.assertNotNull("Data on demand for 'Carta' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Carta' failed to provide an identifier", id);
        obj = Carta.findCarta(id);
        boolean modified =  dod.modifyCarta(obj);
        Integer currentVersion = obj.getVersion();
        Carta merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Carta' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CartaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Carta' failed to initialize correctly", dod.getRandomCarta());
        Carta obj = dod.getNewTransientCarta(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Carta' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Carta' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Carta' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CartaIntegrationTest.testRemove() {
        Carta obj = dod.getRandomCarta();
        Assert.assertNotNull("Data on demand for 'Carta' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Carta' failed to provide an identifier", id);
        obj = Carta.findCarta(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Carta' with identifier '" + id + "'", Carta.findCarta(id));
    }
    
}
