// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.programacion2.demo1.entidades;

import ar.edu.um.programacion2.demo1.entidades.Mazo;
import ar.edu.um.programacion2.demo1.entidades.MazoDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect MazoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MazoDataOnDemand: @Component;
    
    private Random MazoDataOnDemand.rnd = new SecureRandom();
    
    private List<Mazo> MazoDataOnDemand.data;
    
    public Mazo MazoDataOnDemand.getNewTransientMazo(int index) {
        Mazo obj = new Mazo();
        setNombre(obj, index);
        return obj;
    }
    
    public void MazoDataOnDemand.setNombre(Mazo obj, int index) {
        String nombre = "nombre_" + index;
        obj.setNombre(nombre);
    }
    
    public Mazo MazoDataOnDemand.getSpecificMazo(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Mazo obj = data.get(index);
        Long id = obj.getId();
        return Mazo.findMazo(id);
    }
    
    public Mazo MazoDataOnDemand.getRandomMazo() {
        init();
        Mazo obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Mazo.findMazo(id);
    }
    
    public boolean MazoDataOnDemand.modifyMazo(Mazo obj) {
        return false;
    }
    
    public void MazoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Mazo.findMazoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Mazo' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Mazo>();
        for (int i = 0; i < 10; i++) {
            Mazo obj = getNewTransientMazo(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
